export default {
  ADD_KEYWORD: "ADD_KEYWORD",
  CLEAR_EVENTS: "CLEAR_EVENTS",
  LOAD_EVENTS: "LOAD_EVENTS",
  REMOVE_KEYWORD: "REMOVE_KEYWORD",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_IS_SETTINGS_VISIBILE: "SET_IS_SETTINGS_VISIBILE"
};
